// Single registry of all tools exposed by this MCP server. Keep this file
// short — adding a new tool = import + push.

import type { ToolDefinition } from './types.js';
import {
  listCatalogProducts,
  getCatalogPlan,
  listRegions,
  listImages,
  getProductDetails,
  listPrepurchaseOsTemplates,
  listCatalogListings,
  listKubernetesVersions,
} from './catalog.js';
import {
  listServices,
  getService,
  getServiceMetrics,
  listBackups,
  getProvisioningState,
  listOsTemplates,
  listUpgradeOptions,
  getServiceIso,
  listServiceSshKeyLibrary,
  getServiceAutorenew,
} from './services.js';
import { listOrders, getOrder } from './orders.js';
import {
  listInvoices,
  getInvoice,
  getCreditBalance,
  getCreditLedger,
  getInvoicePayPreview,
  listPaymentMethods,
  getBillingCampaign,
  getBonusBalance,
  getBonusLedger,
  getBillingAlert,
  getBillingState,
} from './billing.js';
import {
  getAccount,
  listSshKeys,
  getAccountLimits,
  listAccountClients,
  getAffiliate,
  getTwoFactorStatus,
  listAccountSshKeys,
  getAccountActivity,
  listAccountEmails,
  listAccountContacts,
} from './account.js';
import { listTickets, getTicket, listTicketDepartments } from './tickets.js';
import {
  listVolumes,
  getVolume,
  listNetworks,
  getNetwork,
  listLoadBalancers,
  getLoadBalancer,
  listLoadBalancerMembers,
  listReservedIps,
  listFirewalls,
  getFirewall,
} from './infra.js';
import {
  listDomains,
  getDomain,
  checkDomainAvailability,
  getTldPricing,
  getDomainNameservers,
  getDomainContacts,
  getDomainDns,
  getDomainManagement,
} from './domains.js';
import {
  getClusterScale,
  listClusterPools,
  getClusterKubeconfig,
  listClusterKubeconfigs,
  downloadClusterKubeconfig,
} from './k8s.js';
import {
  listProxies,
  getProxyCatalog,
  getProxy,
  getProxyList,
  getProxyAuth,
  listGbResidentialCountries,
  listGbRotationIntervals,
  listProxyRequests,
  getProxyRequestList,
  getProxyReplacements,
} from './proxies.js';
import {
  setServiceHostname,
  deployService,
  destroyService,
  resizeService,
  upgradeService,
  renewService,
  cancelService,
  setServiceAutorenew,
  createServiceBackup,
  mountServiceIso,
  unmountServiceIso,
  setServicePassword,
  startService,
  stopService,
  rebootService,
  reinstallService,
  resetServicePassword,
  addServiceSshKey,
  addServiceSshKeyToLibrary,
  applyServiceSshKeyLibrary,
} from './services-write.js';
import {
  setClusterScale,
  addClusterPool,
  updateClusterPool,
  deleteClusterPool,
  renameClusterPool,
  enableClusterHa,
  createClusterKubeconfig,
  revokeClusterKubeconfig,
} from './k8s-write.js';
import {
  createVolume,
  deleteVolume,
  attachVolume,
  detachVolume,
  createNetwork,
  deleteNetwork,
  attachNetworkVm,
  reserveIp,
  releaseReservedIp,
  attachReservedIp,
  detachReservedIp,
} from './infra-write.js';
import {
  createFirewall,
  deleteFirewall,
  addFirewallRule,
  deleteFirewallRule,
  attachFirewall,
  detachFirewall,
  createLoadBalancer,
  deleteLoadBalancer,
  addLoadBalancerMember,
  removeLoadBalancerMember,
} from './firewall-lb-write.js';

export const TOOLS: ToolDefinition[] = [
  // Catalog (un-authed surface, "what can I deploy?")
  listCatalogProducts,
  getCatalogPlan,
  listRegions,
  listImages,
  getProductDetails,
  listPrepurchaseOsTemplates,
  listCatalogListings,
  listKubernetesVersions,
  // Services ("what do I have running?")
  listServices,
  getService,
  getServiceMetrics,
  listBackups,
  getProvisioningState,
  listOsTemplates,
  listUpgradeOptions,
  getServiceIso,
  listServiceSshKeyLibrary,
  getServiceAutorenew,
  // Orders ("what have I purchased?")
  listOrders,
  getOrder,
  // Billing ("how much am I spending?")
  listInvoices,
  getInvoice,
  getCreditBalance,
  getCreditLedger,
  getInvoicePayPreview,
  listPaymentMethods,
  getBillingCampaign,
  getBonusBalance,
  getBonusLedger,
  getBillingAlert,
  getBillingState,
  // Support ("any open tickets?")
  listTickets,
  getTicket,
  listTicketDepartments,
  // Account ("who am I + what are my keys?")
  getAccount,
  listSshKeys,
  getAccountLimits,
  listAccountClients,
  getAffiliate,
  getTwoFactorStatus,
  listAccountSshKeys,
  getAccountActivity,
  listAccountEmails,
  listAccountContacts,
  // Cloud infrastructure ("what storage / networks / LBs / IPs / firewalls do I have?")
  listVolumes,
  getVolume,
  listNetworks,
  getNetwork,
  listLoadBalancers,
  getLoadBalancer,
  listLoadBalancerMembers,
  listReservedIps,
  listFirewalls,
  getFirewall,
  // Domains ("what domains do I own + is this name available?")
  listDomains,
  getDomain,
  checkDomainAvailability,
  getTldPricing,
  getDomainNameservers,
  getDomainContacts,
  getDomainDns,
  getDomainManagement,
  // Managed Kubernetes ("scale / pools / kubeconfig for my cloud-k8s clusters")
  getClusterScale,
  listClusterPools,
  getClusterKubeconfig,
  listClusterKubeconfigs,
  downloadClusterKubeconfig,
  // Proxies ("residential proxy services — ISP plans + GB Residential buckets")
  listProxies,
  getProxyCatalog,
  getProxy,
  getProxyList,
  getProxyAuth,
  listGbResidentialCountries,
  listGbRotationIntervals,
  listProxyRequests,
  getProxyRequestList,
  getProxyReplacements,

  // --- WRITE / ACTION TOOLS (Parity Phase B) ---
  // Services — writes
  setServiceHostname,
  // Services — writes (lifecycle / spend)
  deployService,
  destroyService,
  resizeService,
  upgradeService,
  renewService,
  cancelService,
  setServiceAutorenew,
  createServiceBackup,
  mountServiceIso,
  unmountServiceIso,
  setServicePassword,
  // Services — actions + keys
  startService,
  stopService,
  rebootService,
  reinstallService,
  resetServicePassword,
  addServiceSshKey,
  addServiceSshKeyToLibrary,
  applyServiceSshKeyLibrary,
  // Managed Kubernetes — writes
  setClusterScale,
  addClusterPool,
  updateClusterPool,
  deleteClusterPool,
  renameClusterPool,
  enableClusterHa,
  createClusterKubeconfig,
  revokeClusterKubeconfig,
  // Cloud infra — writes (volumes / networks / reserved-ips)
  createVolume,
  deleteVolume,
  attachVolume,
  detachVolume,
  createNetwork,
  deleteNetwork,
  attachNetworkVm,
  reserveIp,
  releaseReservedIp,
  attachReservedIp,
  detachReservedIp,
  // Cloud infra — writes (firewalls / load-balancers)
  createFirewall,
  deleteFirewall,
  addFirewallRule,
  deleteFirewallRule,
  attachFirewall,
  detachFirewall,
  createLoadBalancer,
  deleteLoadBalancer,
  addLoadBalancerMember,
  removeLoadBalancerMember,
];

export function findTool(name: string): ToolDefinition | undefined {
  return TOOLS.find((t) => t.name === name);
}
